// Data for the play-call simulator (playcall/): a custom playbook's formations, sets, alignments and play art.
// usage: node tools/playcall-data.mjs [book.json] [sets.json]   (default: the FUSION port)  -> playcall/data.js
// Play art is approximated from the assignment steps, like tools/m24/preview-fusion.mjs.
import { readFileSync, writeFileSync } from "node:fs";

const bookFile = process.argv[2] ?? "playbooks/FUSION.json";
const specFile = process.argv[3] ?? "playbooks/sets/fusion-sets.json";
const L = f => JSON.parse(readFileSync("data/library/" + f, "utf8"));
const sets = L("sets.json"), plays = L("plays.json"), A = L("assignments.json");
const book = JSON.parse(readFileSync(bookFile, "utf8"));
const spec = JSON.parse(readFileSync(specFile, "utf8"));
const AROOT = "football/Gameplay/playbooks/PlayLibrary/Assignments/";
const playByAsset = new Map(plays.map(p => [p.asset, p]));
const setByAsset = new Map(sets.map(s => [s.asset, s]));
const r1 = v => Math.round(v * 10) / 10;
const typeOf = pos => /HB|3DRB|PWHB/.test(pos) ? "HB" : /FB/.test(pos) ? "FB" : /SLWR|_WR/.test(pos) ? "WR" : /LASTKEYOFFENSE|_TE/.test(pos) ? "TE" : /QB/.test(pos) ? "QB" : "OL";

function stepsFor(entry, slot, src) {
  const a = entry.players?.[slot];
  if (a && typeof a === "object") {
    const tpl = (A[AROOT + (a.template ?? "")]?.steps ?? A[src.assignments[slot]]?.steps ?? []).filter(x => x.type !== "None" && !(a.drop ?? []).includes(x.type));
    const kept = a.keep ? tpl.slice(0, a.keep < 0 ? tpl.length : a.keep) : [];
    return [...(a.prepend ?? []), ...kept, ...a.steps];
  }
  if (typeof a === "string") return A[AROOT + a]?.steps ?? [];
  return A[src.assignments[slot]]?.steps ?? [];
}

// one player's art: motion segments, then the route/run path; kind = route | vip | option | block | carry
function art(entry, n, j, src) {
  const p = n[j];
  let x = p.x, y = p.y, path = [[x, y]], motion = [], kind = "route", carry = false;
  for (const st of stepsFor(entry, j, src)) {
    if (st.type === "OverrideFormPos") { motion.push([x, y, st.offsetX, st.offsetY]); x = st.offsetX; y = st.offsetY; path = [[x, y]]; }
    else if (st.type === "AutoMotion") { for (const w of st.waypoints) { const q = w.position ?? w; motion.push([x, y, q.x, q.y]); x = q.x; y = q.y; } path = [[x, y]]; }
    else if (["RunRoute", "MoveDirection", "ReceiveHandoff", "HeadTurnRunRoute"].includes(st.type)) {
      x += st.distance * Math.cos(st.direction * Math.PI / 180); y += st.distance * Math.sin(st.direction * Math.PI / 180); path.push([x, y]);
    } else if (/Block/.test(st.type)) { if (path.length < 2) kind = "block"; }
    else if (st.type === "OptionRoute") kind = "option";
    if (st.type === "ReceiveHandoff" || st.type === "RecievePitch") carry = true;
  }
  if (carry && /Run|Option|Sneak|JetSweep/.test(src.offensePlayType) && !/RPO|Pass/.test(src.offensePlayType)) kind = "carry";
  if (entry.vip === j && kind !== "block") kind = "vip";
  const out = { kind };
  if (motion.length) out.motion = motion.map(m => m.map(r1));
  if (path.length > 1) out.path = path.map(([a, b]) => [r1(a), r1(Math.min(b, 26))]);
  return out;
}

const formations = [];
for (const f of book.formations) {
  if (!Array.isArray(f.sets)) continue;
  const fo = { name: f.formation, sets: [] };
  for (const bs of f.sets) {
    const s = spec.sets.find(x => x.name === bs.set && x.formation.split("/").at(-1).replace(/_/g, " ") === f.formation);
    if (!s) continue;
    const n = setByAsset.get(s.base).movements.Normal.map(p => ({ ...p }));
    for (const p of s.positions) Object.assign(n[p.slot], { x: p.x, y: p.y });
    const players = n.map((p, j) => ({ t: j === 0 ? "QB" : j >= 6 ? "OL" : typeOf(p.pos), x: r1(p.x), y: r1(p.y) }));
    const byName = new Map(s.plays.map(e => [e.name, e]));
    const ps = [];
    for (const bp of bs.plays) {
      const e = byName.get(bp.play);
      if (!e) continue;
      const src = playByAsset.get(e.from);
      ps.push({ name: e.name, audible: bp.audible ?? 0, art: players.map((_, j) => j === 0 ? null : art(e, n, j, src)) });
    }
    fo.sets.push({ name: s.name, players, plays: ps });
  }
  if (fo.sets.length) formations.push(fo);
}
const out = { book: book.name, formations };
writeFileSync("playcall/data.js", `// generated by tools/playcall-data.mjs from ${bookFile}\nwindow.PLAYBOOK = ${JSON.stringify(out)};\n`);
console.log(`playcall/data.js: ${formations.length} formations, ${formations.reduce((a, f) => a + f.sets.length, 0)} sets, ${formations.reduce((a, f) => a + f.sets.reduce((b, s) => b + s.plays.length, 0), 0)} plays`);
