// Play art engine: assignment steps → drawable paths (FORMATS.md "Play art is generated by the game from these steps").
//
// Conventions (the field renderer and the designer depend on them)
// - Coordinates are field yards (+x right, +y upfield, LOS y = 0, ball at x = 0). Nothing is rounded.
// - `players` follow the set's Normal slot order; `paths` are grouped by slot in slot order, and within a slot in the
//   order the player runs them: preset (pre-snap shift, dashed) → realign (OverrideFormPos / DefMovement, dotted) →
//   motion (AutoMotion) → the main path(s) → option pitch path. Every path starts where the previous one ended.
// - Main path kinds: ballcarrier → "run"; QB drops / handoff turns / rollouts → "qb"; a path that ends in a block
//   (PassBlock / RunBlock / LeadBlock / WedgeBlock) → "block" (cap "block" = T); pass routes → "route", or "primary"
//   for the vip slot; defenders: "rush" (PassRush), "coverage" (to a zone centre, man stub); pitch man → "option".
// - Vertices: one per leg end (RunRoute/MoveDirection/ReceiveHandoff/RecievePitch/HeadTurnRunRoute/QBScramble/
//   HandOffTurn/OptionRun; `step` = step index, no `cut`), one per ReceiverCut / RunRouteFakeOut (same point index as
//   the leg end before it; `cut` = cutType or fakeout, `cutDir` = cut direction) and, on motion paths, one per
//   waypoint (`step` = the AutoMotion step; waypoint k is points[k + 1]). Synthetic points (curl hooks, RunEndZone
//   extensions, pull/lead geometry, block stubs) carry no vertex.
// - Cut styles (v2 "Cuts are visible"): every ReceiverCut / RunRouteFakeOut vertex carries `style` (cutStyle()):
//   "speed" (22/45, drawn rounded), "hard" (67/90/90_INSIDE, sharp + plant tick), "fake" (double moves and jukes, zig
//   mark), "turnback" (curl/comeback/180/smash/screen: hook when it ends the route), "settle" (DRAG_STOP: settle bar).
// - Curls: a route whose last movement step is a turn-back ReceiverCut (CURL, HITCH_COMEBACK*, 180*, HINGECOMEBACK,
//   SMASH*) gets a 1.5 yd hook (three 0.5 yd segments turning 60°/120°/170° toward the cut side) after the cut vertex,
//   then the arrow. A DRAG_STOP at the end draws no hook: its vertex is the route's last point (settle bar).
// - Presets: preset entries are matched to Normal slots by `slot` (2026-10-04 export), else by (pos, depth).
// - flip mirrors the finished art (x → −x, facing/direction 180 − d, cutDir LEFT ↔ RIGHT). This is equivalent to
//   mirroring the inputs (waypoints, OverrideFormPos, gaps Left ↔ RIGHT, runHole odd ↔ even) and is exactly symmetric.
//   artForPlay additionally applies the set's flipAssign partners (withFlipPartners): same geometry, but the player
//   drawn at each mirrored spot is the one the game puts there.
import type { Catalog } from "./catalog";
import { add, angleDeg, DEG, len, mirrorDeg, polar, sub } from "./geometry";
import { glyphFor, slotLabel } from "./positions";
import { spyZone, ZONE_STEPS, zoneSpec } from "./zones";
import type {
  AlignmentPos,
  ArtBounds,
  ArtCap,
  ArtKind,
  ArtOptions,
  ArtPath,
  ArtPlayer,
  ArtVertex,
  ArtZone,
  PlayArt,
  ResolvedPlay,
  SetDef,
  Side,
  Step,
  Vec,
  ZoneKind,
} from "./types";

// ───────────────────────────── cut styles ─────────────────────────────

/**
 * How a route vertex is drawn (ARCHITECTURE "Cuts are visible"):
 * - "speed": rounded corner — the receiver bends the route at speed (22° / 45° cuts);
 * - "hard": sharp corner with a small plant tick (67° / 90° / 90° inside);
 * - "fake": a double move or juke — a small zig mark at the vertex (stutter, out-and-up, post-corner…);
 * - "turnback": curl / comeback / hitch / 180 / smash / screen — a hook back when it ends the route;
 * - "settle": DRAG_STOP — the route ends in a short perpendicular settle bar.
 */
export type CutStyle = "speed" | "hard" | "fake" | "turnback" | "settle";

declare module "./types" {
  interface ArtVertex {
    /** Cut style for the renderer (ReceiverCut / RunRouteFakeOut vertices; see cutStyle() in model/art.ts). */
    style?: CutStyle;
  }
}

const CUT_PREFIX = "RECEIVER_CUT_ANGLE_";
const SPEED_CUTS = /^(22|45)$/;
const HARD_CUTS = /^(67|90|90_INSIDE)$/;
const FAKE_CUTS = /^(STUTTER|STUTTER_STREAK|SHAKE|OUT_AND_UP|HITCH_GO_(INSIDE|OUTSIDE)|STICKNOD|SLANT_AND_GO|POSTCORNER|ZIG|HESITATION)$/;
const TURN_CUTS = /^(CURL|HITCH_COMEBACK(_INSIDE)?|HINGECOMEBACK|180(_PARTIAL)?|SMASH(_QUICK)?|SCREEN(_BACKPEDAL_(SHORT|LONG))?|BUBBLE_SCREEN(_SHORT)?)$/;

/**
 * Cut style of a ReceiverCut cutType ("RECEIVER_CUT_ANGLE_45" or just "45") or a RunRouteFakeOut fakeout type
 * ("JukeLeft45Degrees", "FakeOut"…), or undefined for cuts that draw as a plain corner (INVALID, NORMAL, DoNothing…).
 */
export function cutStyle(cut: string | undefined): CutStyle | undefined {
  if (!cut) return undefined;
  const c = cut.startsWith(CUT_PREFIX) ? cut.slice(CUT_PREFIX.length) : cut;
  if (SPEED_CUTS.test(c)) return "speed";
  if (HARD_CUTS.test(c)) return "hard";
  if (c === "DRAG_STOP") return "settle";
  if (TURN_CUTS.test(c)) return "turnback";
  if (FAKE_CUTS.test(c)) return "fake";
  if (/^(FakeOut|Juke)/i.test(c)) return "fake";
  return undefined;
}

/** Plain-language names for the cut styles (legends, the guide, the cut picker). */
export const CUT_STYLE_INFO: Record<CutStyle, { label: string; hint: string }> = {
  speed: { label: "Speed Cut", hint: "Rounded corner: the receiver bends the route without slowing down (22° / 45°)." },
  hard: { label: "Hard Cut", hint: "Sharp corner: the receiver plants and breaks (67° / 90°)." },
  fake: { label: "Double Move", hint: "Zig mark: the receiver sells a fake here, then keeps going (stutter, out-and-up, post-corner…)." },
  turnback: { label: "Turn Back", hint: "Hook: the receiver stops and turns back to the ball (curl, comeback, hitch, smash, screen)." },
  settle: { label: "Settle", hint: "Bar: the receiver stops in the open space and waits for the ball (drag stop)." },
};

// ───────────────────────────── tunables (yards / degrees) ─────────────────────────────

/** Where rushers aim when a PassRush has no direction. */
const QB_SPOT: Vec = { x: 0, y: -6 };
/** Lateral centre of each gap at the LOS (A = C–G, B = G–T, C = outside T, D = outside TE, E, OUTSIDE). */
export const GAP_X: Record<string, number> = { A: 0.85, B: 2.5, C: 4.2, D: 5.9, E: 7.6, OUTSIDE: 10 };
const HOOK_TURNS = [60, 120, 170];
const HOOK_SEG = 0.5;
const RUN_EXTEND = 5;
const HANDOFF_TURN = 1.5;
const MIN_DROP = 0.8;
const PULL_DEPTH = 0.8;
/** Read-option mesh: the QB shifts this far toward the back (lateral, upfield) before he gives or keeps. */
const MESH_X = 1.4;
const MESH_Y = 0.4;
/** The keeper that follows a mesh: direction away from the back (90 ∓ this) and length. */
const KEEP_SPREAD = 40;
const KEEP_LEN = 6;
/** A QB move at least this far sideways is a boot / rollout / sprint-out: its path ends in an arrow. */
const BOOT_LATERAL = 3;

const LEG_TYPES = new Set(["RunRoute", "MoveDirection", "ReceiveHandoff", "RecievePitch", "HeadTurnRunRoute"]);
const ROUTE_LEGS = new Set(["RunRoute", "HeadTurnRunRoute"]);
const RECEIVE_TYPES = new Set(["ReceiveHandoff", "RecievePitch", "RecUserHandoff", "GetBall", "KickOffCatch"]);
const TURN_BACK_RE = /^RECEIVER_CUT_ANGLE_(CURL|HITCH_COMEBACK(_INSIDE)?|180(_PARTIAL)?|DRAG_STOP|HINGECOMEBACK|SMASH(_QUICK)?)$/;

const num = (v: unknown, fallback: number): number => (typeof v === "number" && Number.isFinite(v) ? v : fallback);
const isNum = (v: unknown): v is number => typeof v === "number" && Number.isFinite(v);

/** Cut types that turn the receiver back toward the QB when they end the route (curl / hitch / sit). */
export function isTurnBackCut(cutType: string): boolean {
  return TURN_BACK_RE.test(cutType);
}

/** Lateral x of a run hole: 0 middle, odd = left (1 A, 3 B, 5 C, 7 D, 9 E), even = right (2 A … 8 D). */
export function holeX(runHole: number): number {
  if (!isNum(runHole) || runHole <= 0) return 0;
  const letter = "ABCDE"[Math.min(4, Math.ceil(runHole / 2) - 1)];
  return GAP_X[letter] * (runHole % 2 === 1 ? -1 : 1);
}

/** Lateral x of a BlockingGap value ("D_GAP_RIGHT", "B_GAP_Left", "RUN_HOLE"…), or undefined (GAP_TOTAL / unknown). */
export function gapX(gap: string, runHole: number): number | undefined {
  if (gap === "RUN_HOLE") return holeX(runHole);
  const m = /^(A|B|C|D|E|OUTSIDE)_GAP_(RIGHT|LEFT)$/i.exec(gap);
  if (!m) return undefined;
  return GAP_X[m[1].toUpperCase()] * (m[2].toUpperCase() === "RIGHT" ? 1 : -1);
}

/** Depth a LeadBlock aims at: through the hole for leads, at the edge for kickouts/traps/whams. */
function leadDepth(technique: string): number {
  if (/KICKOUT|TRAP|WHAM|BACKSIDE_CUTOFF/.test(technique)) return 0.5;
  if (/PULL_INSIDE/.test(technique)) return 1;
  if (/OUTSIDE/.test(technique)) return 2;
  return 1.5; // LEAD_THROUGH_HOLE, LEAD_HOLE_LAST, PULL_LEAD_HOLE, LEAD_HOLE_BACKSIDE
}

/**
 * QB drop / rollout vector for a QBScramble step (before flipping), or undefined when the QB stays put
 * (DROP_TYPEENUM_NONEVALUE with no distance — e.g. after a handoff).
 */
export function qbDropVector(step: Step): Vec | undefined {
  const distance = num(step.distance, 0);
  if (distance > 0) return polar(num(step.direction, 270), distance); // explicit boots / sprint-outs
  const t = String(step.dropBackType ?? "").replace(/^DROP_TYPEENUM_(QBDROP_)?/, "");
  const right = /(_RT|_RIGHT)$/.test(t);
  const left = /(_LT|_LEFT)$/.test(t);
  const back = (yd: number, lateral = 0) => polar(270 + lateral * (right ? 1 : left ? -1 : 0), Math.max(MIN_DROP, yd));
  if (t === "QB_SNEAK") return polar(90, 1.5);
  if (/ROLLOUT|SPEED_PA|DASH_GUN/.test(t)) return polar(right ? 330 : left ? 210 : 270, 7);
  if (/SCREEN/.test(t)) return back(4, 20);
  if (/DRAW|COUNTER_GUN/.test(t)) return back(1, 10);
  if (/PUMP/.test(t)) return t === "PUMP_FAKE" ? back(3) : back(1, 15);
  if (/SLIP/.test(t)) return back(2);
  if (t === "SG_0_STEP") return back(0);
  if (/^SG_1_STEP/.test(t)) return back(1, 15);
  if (/SHOTGUN_3_STEP|SG_3_STEP|3_STEP_PISTOL/.test(t)) return back(2);
  if (/SHOTGUN_5_STEP|SG_5_STEP|5_STEP_PISTOL/.test(t)) return back(3);
  if (/^1_STEP|FAKESPIKE_1STEP/.test(t)) return back(1.5);
  if (/^3_STEP|FAKESPIKE_3STEP/.test(t)) return back(3);
  if (/^5_STEP/.test(t)) return back(5);
  if (/^7_STEP/.test(t)) return back(7);
  return undefined;
}

/**
 * Ballcarrier slots: a RunEndZone runner who receives the ball (handoff / pitch / catch) or an option QB; if nobody
 * qualifies (QB draws, sneaks, fake punts), every RunEndZone runner. Fakes (RunEndZone without the ball while
 * someone else receives) stay routes.
 */
export function findBallcarriers(slots: Step[][]): Set<number> {
  const found = new Set<number>();
  slots.forEach((steps, i) => {
    const runs = steps.some((s) => s.type === "RunEndZone");
    if ((runs && steps.some((s) => RECEIVE_TYPES.has(s.type))) || steps.some((s) => s.type === "OptionRun")) found.add(i);
  });
  if (!found.size) slots.forEach((steps, i) => steps.some((s) => s.type === "RunEndZone") && found.add(i));
  return found;
}

// ───────────────────────────── option routes ─────────────────────────────

/**
 * The branches of an option route, as point lists after the stem end `at` (heading `h`). The library keeps the choices
 * as references we can't read (optionRouteId is empty), but the route type names them: RR_Option_Hitch_Fade = hitch or
 * fade, RR_Option_Curl_Post_Seam = curl, post or seam. In / out are relative to the field (toward / away from the
 * nearer sideline); a receiver in the middle breaks the way he is already heading.
 */
const OPTION_TOKENS: Record<string, string> = {
  curl: "hook",
  hitch: "hook",
  stop: "hook",
  fade: "fade",
  streak: "seam",
  seam: "seam",
  bender: "seam",
  out: "out",
  in: "in",
  dig: "dig",
  drag: "drag",
  slant: "slant",
  post: "post",
  corner: "corner",
  comeback: "comeback",
  juke: "in",
};

export function optionBranches(routeType: string | undefined, at: Vec, h: number): Vec[][] {
  const name = String(routeType ?? "").replace(/^AssignRouteType_/, "");
  if (!/^RR_Option_/.test(name)) return [];
  const tokens = name
    .replace(/^RR_Option_/, "")
    .split("_")
    .map((t) => t.toLowerCase());
  const kinds: string[] = [];
  for (const t of tokens) {
    const k = OPTION_TOKENS[t];
    if (k && !kinds.includes(k)) kinds.push(k);
  }
  // HB choice routes and the generic "Option Route" name no shape: the usual two breaks.
  if (!kinds.length) kinds.push("in", "out");
  // Outward = away from the middle; a receiver on the hash goes the way his stem leans.
  const lean = Math.cos(h * DEG);
  const out: 1 | -1 = Math.abs(at.x) > 0.5 ? (at.x > 0 ? 1 : -1) : lean >= 0 ? 1 : -1;
  const toward = (outward: boolean, upDeg: number) => (outward === (out === 1) ? upDeg : 180 - upDeg); // upDeg: angle above the sideline direction
  const leg = (dir: number, d: number): Vec => add(at, polar(dir, d));
  const result: Vec[][] = [];
  for (const k of kinds) {
    switch (k) {
      case "hook": {
        const pts: Vec[] = [leg(h, 0.5)];
        const side = out === 1 ? -1 : 1; // hooks bend back toward the QB, inside
        for (const turn of HOOK_TURNS) pts.push(add(pts[pts.length - 1], polar(h + side * turn, HOOK_SEG)));
        result.push(pts);
        break;
      }
      case "fade":
        result.push([leg(toward(true, 80), 14)]);
        break;
      case "seam":
        result.push([leg(90, 14)]);
        break;
      case "out":
        result.push([leg(toward(true, 8), 8)]);
        break;
      case "in":
        result.push([leg(toward(false, 8), 9)]);
        break;
      case "dig":
        result.push([leg(toward(false, 3), 11)]);
        break;
      case "drag":
        result.push([leg(toward(false, 0), 13)]);
        break;
      case "slant":
        result.push([leg(toward(false, 45), 8)]);
        break;
      case "post":
        result.push([leg(toward(false, 60), 14)]);
        break;
      case "corner":
        result.push([leg(toward(true, 60), 14)]);
        break;
      case "comeback": {
        const top = leg(h, 1.5);
        result.push([top, add(top, polar(toward(true, -60), 5))]);
        break;
      }
    }
  }
  return result;
}

// ───────────────────────────── per-slot walker ─────────────────────────────

interface Role {
  slot: number;
  isQB: boolean;
  isOL: boolean;
  ballcarrier: boolean;
  defense: boolean;
  vip: boolean;
}

interface Shared {
  paths: ArtPath[];
  zones: ArtZone[];
  runHole: number;
  showPassPro: boolean;
  /** Direction of OL run-block stubs (leans toward the run hole on run plays). */
  olRunDir: number;
  /** Where the QB's option keep ends (pitch men follow it), else the QB's snap spot. */
  qbRef?: Vec;
  /** Side the QB meshes toward on a read option: +1 right, −1 left (where the back runs). */
  meshSide: 1 | -1;
}

interface Pen {
  points: Vec[];
  vertices: ArtVertex[];
  route: boolean;
  label?: string;
  /** Last ReceiverCut after the last leg (a cut that ends the route). */
  endCut?: { cut: string; dir: string };
  /** A QB path that includes a boot / rollout (drawn with an arrow; drops stay plain). */
  boot?: boolean;
}

/** Walks one slot's steps with a cursor + heading, emitting paths (and zones) into `sh`. */
class SlotWalker {
  private pen: Pen | null = null;
  private cur: Vec;
  private heading: number;
  private pull = false;
  /** A block already finished this slot's main path (a trailing RunBlock adds nothing). */
  private blocked = false;
  private readonly firstOut: number;
  /** Upfield for this player's side (return teams block toward −y). */
  private readonly forward: number;

  constructor(
    private readonly role: Role,
    start: Vec,
    private readonly sh: Shared,
    private readonly routeType?: string,
  ) {
    this.cur = start;
    this.forward = role.defense ? 270 : 90;
    this.heading = this.forward;
    this.firstOut = sh.paths.length;
  }

  private begin(): Pen {
    return (this.pen ??= { points: [this.cur], vertices: [], route: false });
  }

  private lineTo(p: Vec, step?: number): void {
    const pn = this.begin();
    const d = sub(p, this.cur);
    if (len(d) > 1e-6) this.heading = angleDeg(d.x, d.y);
    pn.points.push(p);
    if (step !== undefined) pn.vertices.push({ index: pn.points.length - 1, step });
    this.cur = p;
  }

  private emit(kind: ArtKind, cap: ArtCap, extra?: Partial<ArtPath>): void {
    const pn = this.pen;
    this.pen = null;
    if (!pn || pn.points.length < 2) return;
    const path: ArtPath = { slot: this.role.slot, kind, points: pn.points, cap };
    if (pn.vertices.length) path.vertices = pn.vertices;
    if (pn.label) path.label = pn.label;
    this.sh.paths.push(Object.assign(path, extra));
  }

  private hasPath(): boolean {
    return !!this.pen && this.pen.points.length >= 2;
  }

  private roleKind(pn: Pen): ArtKind {
    const r = this.role;
    if (r.ballcarrier) return "run";
    if (r.defense) return "coverage";
    if (r.isQB && !pn.route) return "qb";
    return r.vip ? "primary" : "route";
  }

  /** End the pending path as a route / run / QB path; curls get their hook. */
  private finishRoute(): void {
    const pn = this.pen;
    if (!pn || pn.points.length < 2) {
      this.pen = null;
      return;
    }
    const kind = this.roleKind(pn);
    // DRAG_STOP settles (the renderer draws a settle bar at the end) instead of hooking back.
    if (pn.endCut && isTurnBackCut(pn.endCut.cut) && cutStyle(pn.endCut.cut) !== "settle" && kind !== "qb") {
      const dir = pn.endCut.dir;
      const h = this.heading;
      // No cut direction: bend toward the middle of the field.
      const s = dir.includes("LEFT") ? 1 : dir.includes("RIGHT") ? -1 : polar(h + 90, 1).x * -this.cur.x >= 0 ? 1 : -1;
      for (const turn of HOOK_TURNS) this.lineTo(add(this.cur, polar(h + s * turn, HOOK_SEG)));
    }
    // QB drops, boots and rollouts end in an arrow too (a 1.5 yd handoff turn stays a plain stub under the QB).
    const qbMoves = kind === "qb" && (pn.boot || pn.points.reduce((d, v, i) => (i ? d + len(sub(v, pn.points[i - 1])) : d), 0) >= 2);
    this.emit(kind, kind === "qb" && !qbMoves ? "none" : "arrow");
  }

  private finishBlock(): void {
    this.blocked = true;
    this.emit("block", "block");
  }

  /** Short block stub (T) from the current point. */
  private stub(dir: number, length: number): void {
    this.pen = null;
    this.lineTo(add(this.cur, polar(dir, length)));
    this.finishBlock();
  }

  private motion(stepIndex: number, waypoints: unknown): void {
    const pts: Vec[] = [];
    for (const w of Array.isArray(waypoints) ? waypoints : []) {
      const p = (w as { position?: { x?: unknown; y?: unknown } } | null)?.position;
      if (p && isNum(p.x) && isNum(p.y)) pts.push({ x: p.x, y: p.y });
    }
    if (!pts.length) return;
    if (this.pen) this.finishRoute();
    const out = this.sh.paths;
    const prev = out.length > this.firstOut ? out[out.length - 1] : undefined;
    const end = prev?.points[prev.points.length - 1];
    // Consecutive motions (a 2nd AutoMotion after AutoMotionSnap) extend the same light-blue path.
    let path = prev && prev.kind === "motion" && end && end.x === this.cur.x && end.y === this.cur.y ? prev : undefined;
    if (!path) {
      path = { slot: this.role.slot, kind: "motion", points: [this.cur], cap: "none", vertices: [] };
      out.push(path);
    }
    for (const p of pts) {
      path.points.push(p);
      path.vertices!.push({ index: path.points.length - 1, step: stepIndex });
      const d = sub(p, this.cur);
      if (len(d) > 1e-6) this.heading = angleDeg(d.x, d.y);
      this.cur = p;
    }
  }

  private leadBlock(stepIndex: number, s: Step): void {
    const tech = String(s.blockingTechnique ?? "");
    const pn = this.begin();
    if (/STALK|CRACK/.test(tech)) {
      // Release legs are already in the pen; finish with a T angled toward the ball.
      const toBall = sub({ x: 0, y: 0 }, this.cur);
      this.lineTo(add(this.cur, polar(len(toBall) > 0.1 ? angleDeg(toBall.x, toBall.y) : 90, 0.75)));
    } else if (/WR_SCREEN_(INSIDE|OUTSIDE)/.test(tech)) {
      const inside = this.cur.x > 0 ? -1 : 1;
      this.lineTo(add(this.cur, { x: (/INSIDE/.test(tech) ? inside : -inside) * 2, y: 2 }));
    } else {
      const gx = gapX(String(s.blockingGap ?? ""), this.sh.runHole);
      const target: Vec = gx === undefined ? add(this.cur, polar(90, 1.5)) : { x: gx, y: leadDepth(tech) };
      if (this.pull) {
        // Pullers drop a step, run flat behind the line, then turn up into the gap.
        const behind = this.cur.y - PULL_DEPTH;
        const sx = Math.sign(target.x - this.cur.x);
        if (Math.abs(target.x - this.cur.x) > 1.2) {
          this.lineTo({ x: this.cur.x + sx * 0.4, y: behind });
          this.lineTo({ x: target.x - sx * 0.6, y: behind });
        } else {
          this.lineTo({ x: this.cur.x, y: behind });
        }
        pn.label = "PULL";
      }
      this.lineTo(target, stepIndex);
    }
    this.pull = false;
    this.finishBlock();
  }

  /** Defender path to a zone (or spy area) centre; the zone itself goes to sh.zones. */
  private zone(stepIndex: number, kind: ZoneKind, spec: { center: Vec; rx: number; ry: number; label: string }): void {
    this.sh.zones.push({ slot: this.role.slot, kind, center: spec.center, rx: spec.rx, ry: spec.ry, label: spec.label });
    if (this.pen) this.finishRoute();
    this.lineTo(spec.center, stepIndex);
    this.emit("coverage", "none");
  }

  run(rawSteps: Step[]): void {
    const steps = rawSteps.filter((s) => s && typeof s.type === "string");
    const legsAfter = (i: number) => steps.slice(i + 1).some((s) => LEG_TYPES.has(s.type));

    for (let i = 0; i < steps.length; i++) {
      const s = steps[i];
      const t = s.type;
      if (t === "None") break;

      if (LEG_TYPES.has(t)) {
        const d = num(s.distance, 0);
        if (d > 0) {
          const pn = this.begin();
          this.lineTo(add(this.cur, polar(num(s.direction, this.heading), d)), i);
          if (ROUTE_LEGS.has(t)) pn.route = true;
          pn.endCut = undefined;
        }
        continue;
      }

      switch (t) {
        case "AutoMotion":
          this.motion(i, s.waypoints);
          break;
        case "InitialAnim":
          if (/PULL/.test(String(s.anim ?? ""))) this.pull = true;
          break;
        case "ReceiverCut":
        case "RunRouteFakeOut": {
          const pn = this.begin();
          const cut = t === "ReceiverCut" ? String(s.cutType ?? "") : String(s.fakeout ?? "FAKEOUT");
          const v: ArtVertex = { index: pn.points.length - 1, cut, step: i };
          const style = cutStyle(cut);
          if (style) v.style = style;
          if (t === "ReceiverCut") {
            v.cutDir = String(s.direction ?? "");
            pn.endCut = { cut, dir: v.cutDir };
          }
          pn.vertices.push(v);
          break;
        }
        case "OptionRoute":
          // The stem is the common part; the game picks a branch by coverage. Show every one.
          this.finishRoute();
          optionBranches(this.routeType, this.cur, this.heading).forEach((alt, k) => {
            this.sh.paths.push({ slot: this.role.slot, kind: "option", points: [this.cur, ...alt], cap: "arrow", dashed: true, alt: true, ...(k === 0 ? { label: "OPT" } : undefined) });
          });
          break;
        case "GetOpen":
        case "ChaseBall":
          this.finishRoute();
          break;
        case "RunEndZone":
          if (this.role.ballcarrier) {
            const up = Math.sin(this.heading * DEG);
            const across = Math.cos(this.heading * DEG);
            // Keep running if already heading upfield; turn upfield after a lateral (sweep / reverse) or backward leg.
            const dir = up >= 0.5 ? this.heading : Math.abs(across) < 0.1 ? 90 : across > 0 ? 70 : 110;
            this.lineTo(add(this.cur, polar(dir, RUN_EXTEND)));
          }
          this.finishRoute();
          break;
        case "QBScramble": {
          const v = qbDropVector(s);
          if (v) {
            this.lineTo(add(this.cur, v), i);
            if (Math.abs(v.x) >= BOOT_LATERAL) this.begin().boot = true;
          }
          break;
        }
        case "HandOffTurn":
          this.lineTo(add(this.cur, polar(num(s.direction, 270), HANDOFF_TURN)), i);
          break;
        case "OptionRun": {
          const rt = String(s.runType ?? "");
          this.lineTo(add(this.cur, polar(/LEFT/.test(rt) ? 165 : /RIGHT/.test(rt) ? 15 : this.heading, 4)), i);
          if (this.role.isQB) this.sh.qbRef = this.cur;
          break;
        }
        case "OptionHandoff": {
          // Read-option / RPO mesh: the QB rides toward the back; a keeper (RunEndZone after the mesh) runs away from him.
          const side = this.sh.meshSide;
          this.lineTo(add(this.cur, { x: side * MESH_X, y: MESH_Y }), i);
          if (this.role.isQB) {
            this.emit("qb", "none");
            if (steps.slice(i + 1).some((x) => x.type === "RunEndZone")) {
              this.lineTo(add(this.cur, polar(90 + side * KEEP_SPREAD, KEEP_LEN)), i);
              this.sh.qbRef = this.cur;
              this.emit("option", "arrow", { dashed: true, label: "KEEP" });
            }
          } else this.pen = null;
          break;
        }
        case "OptionFollow": {
          // Pitch man: trails the QB's keep at (offsetX, offsetY); his lead-in legs belong to the same dashed path.
          const ref = this.sh.qbRef;
          if (ref && isNum(s.offsetX) && isNum(s.offsetY)) {
            this.lineTo({ x: ref.x + s.offsetX, y: ref.y + s.offsetY }, i);
            this.emit("option", "arrow", { dashed: true });
          }
          break;
        }
        case "PassBlock":
          if (num(s.time, 0) > 0 && legsAfter(i)) break; // block, then release into a route drawn from here
          if (this.hasPath()) this.finishBlock();
          else if (/ProtectReceiver/.test(String(s.flags ?? ""))) this.stub(this.forward, 0.6); // screen convoy: T in front
          else if (!this.role.isOL || this.sh.showPassPro) this.stub(this.forward + 180, 1); // protection: step back
          else this.blocked = true;
          break;
        case "RunBlock":
          if (this.hasPath()) this.finishBlock();
          else if (!this.blocked) this.stub(this.role.isOL && !this.role.defense ? this.sh.olRunDir : this.forward, 1);
          break;
        case "WedgeBlock":
          if (this.hasPath()) this.finishBlock();
          else this.stub(num(s.direction, this.forward), 1);
          break;
        case "LeadBlock":
          this.leadBlock(i, s);
          break;
        case "PassRush": {
          const c = this.cur;
          const dir = isNum(s.direction) ? s.direction : angleDeg(QB_SPOT.x - c.x, QB_SPOT.y - c.y);
          let dist = Math.max(num(s.distance, 0), 2.5);
          // Blitzers from depth: carry the arrow through the LOS so it reads as a rush.
          const down = -Math.sin(dir * DEG);
          if (down > 0.3) dist = Math.max(dist, Math.min(12, (c.y + 2) / down));
          if (this.pen) this.finishRoute();
          this.lineTo(add(c, polar(dir, dist)), i);
          this.emit("rush", "arrow");
          break;
        }
        case "ReadAndBlitz": {
          // QB spy: shadows the QB from a short area and only rushes if he runs.
          const z = spyZone(this.cur);
          this.zone(i, z.kind, z);
          break;
        }
        case "ManCoverage":
          if (this.pen) this.finishRoute();
          this.lineTo(add(this.cur, polar(270, 1.5)), i);
          this.emit("coverage", "dot", { label: "MAN" });
          break;
        case "DefMovement":
          if (isNum(s.offsetX) && isNum(s.offsetY)) {
            if (this.pen) this.finishRoute();
            this.lineTo({ x: s.offsetX, y: s.offsetY }, i);
            this.emit("realign", "none");
          }
          break;
        default: {
          const zs = ZONE_STEPS[t];
          const spec = zs ? zoneSpec(String(s[zs.field] ?? "")) : undefined;
          if (zs && spec) this.zone(i, zs.kind, spec);
          // Mechanics (CannedHandoff, HandOffGive, HandoffFake, PitchBall, OptionHandoff…), Delay, FaceDirection,
          // DefAlignment, ShowBlitz, kicks… don't draw by themselves.
        }
      }
    }
    this.finishRoute();

    // A motion that nothing follows ends with an arrow.
    const out = this.sh.paths;
    const last = out.length > this.firstOut ? out[out.length - 1] : undefined;
    if (last?.kind === "motion") last.cap = "arrow";
  }
}

// ───────────────────────────── art assembly ─────────────────────────────

const EMPTY_BOUNDS: ArtBounds = { minX: -10, maxX: 10, minY: -8, maxY: 12 };

export function emptyArt(flipped = false): PlayArt {
  return { players: [], paths: [], zones: [], bounds: { ...EMPTY_BOUNDS }, flipped };
}

/**
 * Preset entry per Normal slot (undefined = the preset doesn't move that slot). Entries are matched by `slot` when the
 * library carries it (2026-10-04 export; e.g. a preset entry whose pos is POSITION_LASTKEYOFFENSE), otherwise by
 * (pos, depth) like older exports. Unmatched entries are ignored.
 */
export function matchPreset(normal: AlignmentPos[], preset: AlignmentPos[] | undefined): (AlignmentPos | undefined)[] {
  const out: (AlignmentPos | undefined)[] = normal.map(() => undefined);
  if (!preset) return out;
  for (const p of preset) {
    if (!p) continue;
    const s = p.slot;
    if (typeof s === "number" && Number.isInteger(s) && s >= 0 && s < normal.length) {
      if (!out[s]) out[s] = p; // a second entry for the same slot is ignored
      continue;
    }
    const i = normal.findIndex((n, k) => !out[k] && n.pos === p.pos && n.depth === p.depth);
    if (i >= 0) out[i] = p;
  }
  return out;
}

/**
 * The set's flip partners: partners[i] = the slot whose spot (mirrored) the player of slot i takes when the play is
 * flipped (AlignmentPos.flipAssign, FORMATS.md §1). Undefined unless every Normal slot carries one and they form a
 * permutation (older exports, hand-made sets) — callers then fall back to the plain mirror.
 */
export function flipPartners(normal: AlignmentPos[] | undefined): number[] | undefined {
  if (!Array.isArray(normal) || !normal.length) return undefined;
  const seen = new Set<number>();
  const out: number[] = [];
  for (const a of normal) {
    const f = a?.flipAssign;
    if (typeof f !== "number" || !Number.isInteger(f) || f < 0 || f >= normal.length || seen.has(f)) return undefined;
    seen.add(f);
    out.push(f);
  }
  return out;
}

/**
 * Who stands where in a flipped play. The game puts the player of slot i on the mirrored spot of slot flipAssign[i]
 * (Y Trips Wk: WR1 ↔ WR2, so WR1 stays on the left as the flanker). The drawn geometry stays the exact mirror and
 * every player/path keeps its assignment slot (vip, reads and paths are per assignment slot, and the route drawn
 * from a spot is that spot's assignment, mirrored); only the identity drawn at each spot — pos, depth, label,
 * glyph — becomes the partner's. Returns `art` itself when it isn't flipped or the set has no usable flipAssign
 * (the plain mirror).
 */
export function withFlipPartners(art: PlayArt, set: SetDef | undefined): PlayArt {
  if (!art.flipped) return art;
  const normal = set?.movements?.Normal;
  const partners = flipPartners(normal);
  if (!normal || !partners || partners.every((p, i) => p === i)) return art;
  const personAt = new Map<number, number>(); // spot (assignment slot) → slot of the player standing there
  partners.forEach((spot, person) => personAt.set(spot, person));
  let changed = false;
  const players = art.players.map((pl) => {
    const person = personAt.get(pl.slot);
    if (person === undefined || person === pl.slot) return pl;
    const a = normal[person];
    changed = true;
    return { ...pl, pos: a.pos, depth: a.depth, label: slotLabel(a.pos, a.depth), glyph: glyphFor(a) };
  });
  return changed ? { ...art, players } : art;
}

function mirrorArt(art: PlayArt): PlayArt {
  const mv = (v: Vec): Vec => ({ x: -v.x, y: v.y });
  const swapDir = (d: string) =>
    d.includes("LEFT") ? d.replace("LEFT", "RIGHT") : d.includes("RIGHT") ? d.replace("RIGHT", "LEFT") : d;
  return {
    players: art.players.map((p) => ({ ...p, base: mv(p.base), at: mv(p.at), snap: mv(p.snap), facing: mirrorDeg(p.facing) })),
    paths: art.paths.map((p) => {
      const q: ArtPath = { ...p, points: p.points.map(mv) };
      if (p.vertices) q.vertices = p.vertices.map((v) => (v.cutDir ? { ...v, cutDir: swapDir(v.cutDir) } : { ...v }));
      return q;
    }),
    zones: art.zones.map((z) => ({ ...z, center: mv(z.center) })),
    bounds: { minX: -art.bounds.maxX, maxX: -art.bounds.minX, minY: art.bounds.minY, maxY: art.bounds.maxY },
    flipped: !art.flipped,
  };
}

function computeBounds(players: ArtPlayer[], paths: ArtPath[], zones: ArtZone[]): ArtBounds {
  let minX = Infinity;
  let maxX = -Infinity;
  let minY = Infinity;
  let maxY = -Infinity;
  const take = (x: number, y: number) => {
    if (x < minX) minX = x;
    if (x > maxX) maxX = x;
    if (y < minY) minY = y;
    if (y > maxY) maxY = y;
  };
  for (const p of players) {
    take(p.base.x, p.base.y);
    take(p.at.x, p.at.y);
    take(p.snap.x, p.snap.y);
  }
  for (const p of paths) for (const v of p.points) take(v.x, v.y);
  for (const z of zones) {
    take(z.center.x - z.rx, z.center.y - z.ry);
    take(z.center.x + z.rx, z.center.y + z.ry);
  }
  return minX <= maxX ? { minX, maxX, minY, maxY } : { ...EMPTY_BOUNDS };
}

/** Which way the QB meshes on an option handoff: toward the back who gets the ball (his first leg, else where he stands). */
function meshSideOf(normal: AlignmentPos[], carriers: ReadonlySet<number>, stepsOf: (i: number) => Step[]): 1 | -1 {
  const qb = normal.findIndex((a) => glyphFor(a) === "qb");
  const qx = qb >= 0 ? num(normal[qb].x, 0) : 0;
  for (const slot of carriers) {
    if (slot === qb) continue;
    const leg = stepsOf(slot).find((s) => LEG_TYPES.has(s.type) && isNum(s.direction) && num(s.distance, 0) > 0);
    const c = leg ? Math.cos(num(leg.direction, 90) * DEG) : 0;
    if (Math.abs(c) > 0.15) return c > 0 ? 1 : -1;
    const dx = num(normal[slot]?.x, 0) - qx;
    if (Math.abs(dx) > 0.3) return dx > 0 ? 1 : -1;
  }
  return 1;
}

/**
 * Compute the art for a set + per-slot steps (slot i ↔ set.movements.Normal[i]). Extra slots without a player are
 * ignored; players without steps just stand. `opts.vip` marks the primary route; `opts.runHole` aims RUN_HOLE blocks.
 */
export function computeArt(set: SetDef, slots: Step[][], opts: ArtOptions = {}): PlayArt {
  const normal = set?.movements?.Normal;
  if (!Array.isArray(normal) || !normal.length) return emptyArt(!!opts.flip);

  const presetList = opts.preset && opts.preset !== "Normal" ? set.movements[opts.preset] : undefined;
  const presets = matchPreset(normal, presetList);
  const glyphs = normal.map((a) => glyphFor(a));
  const side: Side = opts.side ?? (glyphs.filter((g) => g === "def").length * 2 > normal.length ? "defense" : "offense");
  const defense = side === "defense";
  const vip = !defense && isNum(opts.vip) ? opts.vip : -1;
  const runHole = isNum(opts.runHole) ? opts.runHole : 0;
  const stepsOf = (i: number): Step[] => (Array.isArray(slots[i]) ? slots[i] : []);
  // Real defenses never carry the ball; return teams (defense side) do.
  const carriers = findBallcarriers(normal.map((_, i) => stepsOf(i)));
  const olRunDir = carriers.size && runHole > 0 ? (runHole % 2 === 1 ? 110 : 70) : 90;

  const sh: Shared = { paths: [], zones: [], runHole, showPassPro: !!opts.showPassPro, olRunDir, meshSide: meshSideOf(normal, carriers, stepsOf) };
  const players: ArtPlayer[] = [];

  normal.forEach((a, slot) => {
    const steps = stepsOf(slot);
    const normalPos: Vec = { x: num(a.x, 0), y: num(a.y, 0) };
    const pre = presets[slot];
    const base: Vec = pre ? { x: num(pre.x, normalPos.x), y: num(pre.y, normalPos.y) } : normalPos;
    const ofp = steps.find((s) => s.type === "OverrideFormPos" && isNum(s.offsetX) && isNum(s.offsetY));
    const at: Vec = ofp ? { x: ofp.offsetX as number, y: ofp.offsetY as number } : base;
    const glyph = glyphs[slot];
    const role: Role = {
      slot,
      isQB: glyph === "qb",
      isOL: glyph === "ol" || glyph === "center",
      ballcarrier: carriers.has(slot),
      defense,
      vip: slot === vip,
    };
    players.push({
      slot,
      pos: a.pos,
      depth: a.depth,
      label: slotLabel(a.pos, a.depth),
      glyph,
      base,
      at,
      snap: at,
      facing: num(pre?.facing ?? a.facing, defense ? 270 : 90),
      stance: typeof ofp?.stance === "string" && ofp.stance ? ofp.stance : (pre?.stance ?? a.stance),
      isVip: slot === vip,
      isBallcarrier: role.ballcarrier,
      motionMan: !!a.motionMan,
      side,
    });

    if (pre && (base.x !== normalPos.x || base.y !== normalPos.y)) {
      sh.paths.push({ slot, kind: "preset", points: [normalPos, base], cap: "arrow", dashed: true });
    }
    if (at.x !== base.x || at.y !== base.y) sh.paths.push({ slot, kind: "realign", points: [base, at], cap: "none" });
    if (role.isQB && !sh.qbRef) sh.qbRef = at;
    new SlotWalker(role, at, sh, opts.routeTypes?.[slot]).run(steps);
  });

  const art: PlayArt = { players, paths: sh.paths, zones: sh.zones, bounds: computeBounds(players, sh.paths, sh.zones), flipped: false };
  return opts.flip ? mirrorArt(art) : art;
}

// ───────────────────────────── memoized art for catalog plays ─────────────────────────────

const ART_CACHE_MAX = 4000;
const artCache = new Map<string, { play: ResolvedPlay; art: PlayArt }>();
let artCacheLib: unknown;

/** Offense or defense for art purposes; special teams by formation type (punt/kickoff teams are offense). */
export function artSideForPlay(catalog: Catalog, play: ResolvedPlay): Side | undefined {
  if (play.side !== "special") return play.side;
  const type = catalog.lib.formationByAsset.get(play.formation)?.type ?? "";
  if (/Offense|Kickoff/i.test(type) && !/Return/i.test(type)) return "offense";
  if (/Defense|Return/i.test(type)) return "defense";
  return undefined;
}

/**
 * Art for a resolved play (library or custom), memoized (LRU, ~4000 entries) by play key + catalog.version (custom
 * plays) + options. Defaults: vip / runHole from the play, side from the play's formation (special → by glyphs).
 * Flipped art also applies the set's flipAssign partners (withFlipPartners: who stands on each mirrored spot).
 */
export function artForPlay(catalog: Catalog, play: ResolvedPlay, opts: ArtOptions = {}): PlayArt {
  if (artCacheLib !== catalog.lib) {
    artCache.clear();
    artCacheLib = catalog.lib;
  }
  const o: ArtOptions = {
    vip: opts.vip ?? play.vip,
    runHole: opts.runHole ?? play.runHole,
    flip: !!opts.flip,
    preset: opts.preset,
    showPassPro: !!opts.showPassPro,
    side: opts.side ?? artSideForPlay(catalog, play),
    routeTypes: play.slots.map((sl) => sl.routeType),
  };
  const key = [
    play.source === "library" ? "L" : `C${catalog.version}`,
    play.key,
    o.vip,
    o.runHole,
    o.flip ? 1 : 0,
    o.preset ?? "",
    o.showPassPro ? 1 : 0,
    o.side ?? "",
  ].join("|");
  const hit = artCache.get(key);
  if (hit && hit.play === play) {
    artCache.delete(key); // refresh LRU position
    artCache.set(key, hit);
    return hit.art;
  }
  const set = catalog.lib.setByAsset.get(play.set);
  const art = set ? withFlipPartners(computeArt(set, play.slots.map((s) => s.steps), o), set) : emptyArt(!!o.flip);
  artCache.set(key, { play, art });
  if (artCache.size > ART_CACHE_MAX) artCache.delete(artCache.keys().next().value as string);
  return art;
}
